name: CI

on:
  workflow_call: ~
  workflow_dispatch: ~

jobs:
  combined:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Cache Node.js modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run install
        # act requires exact version numbers while github is OK with just major versions
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
      - name: Check if lockfile was modified
        run: |
          if [[ `git status --porcelain yarn.lock` ]]; then
            echo "The yarn.lock file has been modified. Please commit the updated lockfile."
            exit 1
          fi
      - name: Run linting
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: lint
      - name: Run typechecking
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: check-types
      - name: Run tests
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: test
      - name: Run build
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build
